aperitivos/urls.py
from django.urls import path

from aperitivos.views import video, indice

app_name = 'aperitivos'
urlpatterns = [
    path('<slug:slug>', video, name='video'),
    path('', indice, name='indice'),
]

base/urls.py
from django.urls import path

from base.views import home

app_name = 'base'
urlpatterns = [
    path('', home, name='home'),
]

modulos/urls.py
from django.urls import path

from modulos import views

app_name = 'modulos'
urlpatterns = [
    path('<slug:slug>', views.detalhe, name='detalhe'),
    path('aulas/<slug:slug>', views.aula, name='aula'),
    path('', views.indice, name='indice'),
]

pypro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('contas/', include('django.contrib.auth.urls')),
    path('', include('base.urls')),
    path('aperitivos/', include('aperitivos.urls')),
    path('modulos/', include('modulos.urls')),
    path('turmas/', include('turmas.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls))
    )

turmas/urls.py
from django.urls import path

from turmas import views

app_name = 'turmas'
urlpatterns = [
    path('', views.indice, name='indice'),
]

aperitivos/models.py
from django.db import models
from django.urls import reverse


class Video(models.Model):
    titulo = models.CharField(max_length=32)
    slug = models.SlugField(max_length=32)
    vimeo_id = models.CharField(max_length=32)
    creation = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('aperitivos:video', args=(self.slug,))

    def __str__(self):
        return f'Video: {self.titulo}'

base/models.py
from django.utils import timezone

from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import gettext_lazy as _
from django.core.mail import send_mail

from django.db import models


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not email:
            raise ValueError('The given username must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(username, email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    An abstract base class implementing a fully featured User model with
    admin-compliant permissions.

    Email and password are required. Other fields are optional.
    """

    first_name = models.CharField(_('first name'), max_length=150, blank=True)
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

modulos/models.py
from django.db import models
from ordered_model.models import OrderedModel
from django.urls import reverse


class Modulo(OrderedModel):
    titulo = models.CharField(max_length=64)
    publico = models.TextField(null=True)
    descricao = models.TextField(null=True)
    slug = models.SlugField(unique=True)
    # aula_set # automático

    class Meta(OrderedModel.Meta):
        pass

    def __str__(self):
        return self.titulo

    def get_absolute_url(self):
        return reverse('modulos:detalhe', kwargs={'slug': self.slug})


class Aula(OrderedModel):
    titulo = models.CharField(max_length=64)
    slug = models.SlugField(unique=True)
    modulo = models.ForeignKey('Modulo', on_delete=models.PROTECT)
    order_with_respect_to = 'modulo'
    vimeo_id = models.CharField(max_length=32)  # defoult=1 na primeira migração

    class Meta(OrderedModel.Meta):
        pass

    def __str__(self):
        return self.titulo

    def get_absolute_url(self):
        return reverse('modulos:aula', kwargs={'slug': self.slug})

turmas/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Turma(models.Model):
    nome = models.CharField(max_length=64)
    slug = models.SlugField(max_length=64)
    inicio = models.DateField()
    fim = models.DateField()
    alunos = models.ManyToManyField(get_user_model(), through='Matricula')


class Matricula(models.Model):
    data = models.DateField(auto_now_add=True)
    usuario = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    turma = models.ForeignKey(Turma, on_delete=models.CASCADE)

    class Meta:
        unique_together = [['usuario', 'turma']]
        ordering = ['turma', 'data']

aperitivos/views.py
from django.shortcuts import render, get_object_or_404
from aperitivos.models import Video


def indice(request):
    videos = Video.objects.order_by('creation').all()
    return render(request, 'aperitivos/indice.html', context={'videos': videos})


def video(request, slug):
    video = get_object_or_404(Video, slug=slug)
    return render(request, 'aperitivos/video.html', context={'video': video})

base/views.py
from django.http import HttpResponse # noqa
from django.shortcuts import render # noqa


def home(request):
    return render(request, 'base/home.html', {})

modulos/views.py
from django.shortcuts import render
from modulos import facade
from django.contrib.auth.decorators import login_required


def detalhe(request, slug):
    modulo = facade.encontrar_modulo(slug)
    aulas = facade.lista_aulas_de_modulo_ordenadas(modulo)
    return render(request, 'modulos/modulo_detalhe.html', {'modulo': modulo, 'aulas': aulas})


@login_required
def aula(request, slug):
    aula = facade.encontrar_aula(slug)
    return render(request, 'modulos/aula_detalhe.html', {'aula': aula})


def indice(request):
    ctx = {'modulos': facade.listar_modulos_com_aulas()}
    return render(request, 'modulos/indice.html', ctx)

turmas/views.py
from django.shortcuts import render


def indice(request):
    return render(request, 'turmas/indice.html')

aperitivos/templates/aperitivos/indice.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Pagina com todos vídeos gratuitos{% endblock title %}

{% block body %}
<div class="container mt-5 mb-5">
    <div class="row">
        <div class="col-md-12">
            <center><h1 class="mt-4 mb-3">Lista de Vídeos Aperitivos</h1></center>
            <ol>
                {% for video in videos %}
                <li><a href="{{ video.get_absolute_url }}">{{ video.titulo | default:"Faltando Titulo"}}</a></li>
                {% empty %}
                <p>Não foi encontrado nenhum vídeo para aperitivo</p>
                {% endfor %}
            </ol>
        </div>
    </div>
</div>
{% endblock body %}

aperitivos/templates/aperitivos/video.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Python Pro João Guilherme-Motivação{% endblock title %}

{% block body %}
<div class="container mt-5 mb-5">
    <div class="row">
        <div class="col-md-12">
            <center><h1 class="mt-4 mb-3">{{ video.titulo | default:"Faltando Titulo" }}</h1></center>
            <div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/{{ video.vimeo_id }}?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479&amp;h=4886bdea4c" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen style="position:absolute;top:0;left:0;width:100%;height:100%;" title="AULA 01 - MOTIVA&amp;Ccedil;&amp;Atilde;O &amp;mdash; Curso de Python Gr&amp;aacute;tis-2aYplgJrPDU"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script>
        </div>
    </div>
</div>
{% endblock body %}

base/templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Python Pro João Guilherme{% endblock title %}</title>

    <meta name="description" content="{% block description %}Página do curso Python Pro João Guilherme{% endblock description %}">
    <meta name="author" content="João Guilherme">
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}" />
    <link href= "{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href= "{% static 'css/style.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>


</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'base:home' %}">Python Pro JG</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" datatoggle="dropdown"
            aria-haspopup="true" aria-expanded="false">Módulos</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for modulo in MODULOS %}
                <a class="dropdown-item" href="{{ modulo.get_absolute_url }}">{{ modulo.titulo }}</a>
                <div class="dropdown-divider"></div>
              {% endfor %}
            </div>
        </li>
    </ul>
  </div>
  {% if user.is_authenticated %}
    <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" datatoggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                  {{ user.first_name }}
              </a>
            </li>
            <a class="btn btn-light" href="{% url 'logout' %}" >Sair</a>
    </ul>
  {% else %}
  <a class="btn btn-light" href="{% url 'login' %}">Login</a>
  {% endif %}
</nav>

{% block body %}{% endblock body %}

<div class="container mt-2">
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <h5 class="card-header">
                            <center>Mais detalhes sobre o instrutor</center>
                        </h5>
                        <div class="card-body">
                            <p class="card-text">
                                <img src="{% static 'img/luciano.jpg' %}" alt="Foto de Luciano Ramalho" class="rounded mx-auto d-block">
                                Ramalho é sócio e professor na <a href="https://www.python.pro.br">Python Pro</a> e autor do Livro Python Fluente.
                                Foi diretor técnico do Brasil Online, primeiro portal da Abril S/A na Web. Liderou times para os portais IDG Now,
                                BOL, UOL, AOL Brasil e outros, usando Python desde 1998. Como instrutor, atendeu clientes como Citibank, CPqD, Serpro,
                                Presidência da República, Globo.com e Itaú. Palestrante em eventos internacionais como FISL, PyCon US e OSCON. Ajudou
                                a criar a Associação Python Brasil e foi seu presidente. É membro da Python Software Foundation e fundador do Garoa Hacker
                                Clube, o primeiro hackerspace do Brasil.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container mt-2">
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <h5 class="card-header">
                            <center>Mais detalhes sobre o desenvolvedor</center>
                        </h5>
                        <div class="card-body">
                            <p class="card-text">
                                <img src="{% static 'img/me.jpg' %}" alt="Foto de João Guilherme" class="rounded mx-auto d-block">
                                Este é um projeto desenvolvido no curso <a href="https://pythonpro.com" >Python Pro</a> com o
                                objetivo de criar uma aplicação de gerenciamento de cursos do autor Luciano Ramalho. O desenvolvedor desse projeto
                                se chama João Guilherme e seus projetos podem ser visto no seu portifólio no <a href="https://github.com/JoaoZati">GitHub</a>
                                O projeto desse site pode ser visto em <a href="https://github.com/JoaoZati/django_devpro_jg">django_devpro_jg</a>.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% include 'base/footer.html' with email_ramalho='ramalho@python.pro.br' only %}

</body>

base/templates/base/footer.html
<footer class="main-footer mt-5 pt-4 text-light">
    <div class="container">
        <div class="row">
            <div class="col">
                <center><h3>Entre em Contato:</h3></center>
                <address>
                    <center><a href="mailto:{{ email_ramalho }}" class="text-light">{{ email_ramalho }}</a></center>
                </address>
                <address>
                    <center><a href="mailto:joaozati@gmail.com" class="text-light">joaozati@gmail.com</a></center>
                </address>
            </div>

        </div>
    </div>
    <div class="rights pb-4">
        <div class="container">
            <div class="row">
                <div class="col">
                    <center>{% now 'd' %} de {% now 'M' %} de {% now 'Y' %}</center>
                </div>

            </div>
        </div>
    </div>

</footer>

base/templates/base/home.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Python Pro João Guilherme-Home{% endblock title %}

{% block body %}
<div class="container mt-2">
    <div class="row">
        <div class="col-md-12">
            <div class="jumbotron">
                <h2>
                    <center>Curso Python com Luciano Ramalho</center>
                </h2>
                <p>
                    <center>Confira em breve mais informações sobre o curso que será ministrado pelo autor do livro:
                            <a href="https://www.oreilly.com/playlists/ba5190c2-d78d-484a-9875-812214b589dd/" target="_blank" >Python Fluente</a></center>
                </p>
                <h4 class="mt-4">
                    <center>Entre para a lista de espera:</center>
                </h4>
                <form action="https://herokuapp.us5.list-manage.com/subscribe/post?u=35d1de4f6415d33aa445a48a4&amp;id=271ce6a76f"
                      method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form"
                      class="validate" target="_blank" novalidate>
                  <div class="form-row align-items-center">
                    <div class="col-auto">
                        <center><label class="sr-only" for="mce-EMAIL">Email</label></center>
                        <center><input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL" placeholder="exemplo@email.com"></center>
                    </div>
                    <div class="col-auto">
                        <center><label class="sr-only" for="mce-FNAME">Nome</label></center>
                        <center><input type="text" value="" name="FNAME" class="required email" id="mce-FNAME" placeholder="Nome"></center>
                    </div>
                    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_35d1de4f6415d33aa445a48a4_271ce6a76f" tabindex="-1" value=""></div>
                    <div class="col-auto mt-2">
                        <center><button type="submit" class="btn btn-primary mb-2">Submit</button></center>
                    </div>
                  </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

base/templates/base/home_pagamento.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Python Pro João Guilherme</title>

    <meta name="description" content="Página do curso Python Pro João Guilherme">
    <meta name="author" content="João Guilherme">
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}" />
    <link href= "{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href= "{% static 'css/style.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>


</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'base:home' %}">Python Pro JG</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    </ul>
  </div>
</nav>
<div class="container mt-2">
    <div class="row">
        <div class="col-md-12">
            <div class="jumbotron">
                <h2 class="mt-5">
                    <center>Curso Python com Luciano Ramalho</center>
                </h2>
                <h4 class="mt-3">
                    <center>Obrigado por escolher adquirir o curso, o pagamento é muito simples:</center>
                </h4>
                <h4  class="mt-3">
                    <center>Basta antes de tudo entrar em contato com o email
                    <a href="mailto:joaozati@gmail.com" class="text-blue">joaozati@gmail.com</a> com o Título:</center>
                </h4>
                <h2  class="mt-3">
                    <center>Comprar Curso Luciano Ramalho</center>
                </h2>
                <h4  class="mt-3">
                     Então enviarei por email um endereço Bitcoin para deposito, basta fazer então o deposito de 0.004 BTC no endereço
                     fornecido, colocar uma mensagem com seu email no pagamento e ou enviar o comprovante de deposíto por email e o curso
                     será liberado imediatamente.</center>
                </h4>
                <h4

                </h4>
                <h4  class="mt-3">
                    <center>Fico no aguardo!</center>
                </h4>

            <div class="row mt-5">
                <div class="col-md-12">
                    <div class="card">
                        <h5 class="card-header">
                            <center>Mais detalhes sobre o instrutor</center>
                        </h5>
                        <div class="card-body">
                            <p class="card-text">
                                <img src="{% static 'img/luciano.jpg' %}" alt="Foto de Luciano Ramalho" class="rounded mx-auto d-block">
                                Ramalho é sócio e professor na <a href="https://www.python.pro.br">Python Pro</a> e autor do Livro Python Fluente.
                                Foi diretor técnico do Brasil Online, primeiro portal da Abril S/A na Web. Liderou times para os portais IDG Now,
                                BOL, UOL, AOL Brasil e outros, usando Python desde 1998. Como instrutor, atendeu clientes como Citibank, CPqD, Serpro,
                                Presidência da República, Globo.com e Itaú. Palestrante em eventos internacionais como FISL, PyCon US e OSCON. Ajudou
                                a criar a Associação Python Brasil e foi seu presidente. É membro da Python Software Foundation e fundador do Garoa Hacker
                                Clube, o primeiro hackerspace do Brasil.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <h5 class="card-header">
                            <center>Mais detalhes sobre o desenvolvedor</center>
                        </h5>
                        <div class="card-body">
                            <p class="card-text">
                                <img src="{% static 'img/me.jpg' %}" alt="Foto de João Guilherme" class="rounded mx-auto d-block">
                                Este é um projeto desenvolvido no curso <a href="https://pythonpro.com" >Python Pro</a> com o
                                objetivo de criar uma aplicação de gerenciamento de cursos do autor Luciano Ramalho. O desenvolvedor desse projeto
                                se chama João Guilherme e seus projetos podem ser visto no seu portifólio no <a href="https://github.com/JoaoZati">GitHub</a>
                                O projeto desse site pode ser visto em <a href="https://github.com/JoaoZati/django_devpro_jg">django_devpro_jg</a>.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<footer class="main-footer mt-5 pt-4 text-light">
    <div class="container">
        <div class="row">
            <div class="col">
                <center><h3>Entre em Contato:</h3></center>
                <address>
                    <center><a href="mailto:ramalho@python.pro.br" class="text-light">ramalho@python.pro.br</a></center>
                </address>
                <address>
                    <center><a href="mailto:joaozati@gmail.com" class="text-light">joaozati@gmail.com</a></center>
                </address>
            </div>

        </div>
    </div>
    <div class="rights pb-4">
        <div class="container">
            <div class="row">
                <div class="col">
                    <center>{% now 'd' %} de {% now 'M' %} de {% now 'Y' %}</center>
                </div>

            </div>
        </div>
    </div>

</footer>
</body>

modulos/templates/modulos/aula_detalhe.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Python Pro João Guilherme-Motivação{% endblock title %}

{% block body %}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="#">Home</a></li>
    <li class="breadcrumb-item"><a href="{{ aula.modulo.get_absolute_url }}">{{ aula.modulo.titulo }}</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ aula.titulo }}</li>
  </ol>
</nav>

<div class="container mt-5 mb-5">
    <div class="row">
        <div class="col-md-12">
            <center><h1 class="mt-4 mb-3">{{ aula.titulo | default:"Faltando Titulo" }}</h1></center>
            <div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/{{ aula.vimeo_id }}?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479&amp;h=4886bdea4c" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen style="position:absolute;top:0;left:0;width:100%;height:100%;" title="AULA 01 - MOTIVA&amp;Ccedil;&amp;Atilde;O &amp;mdash; Curso de Python Gr&amp;aacute;tis-2aYplgJrPDU"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script>
        </div>
    </div>
</div>

{% endblock body %}

modulos/templates/modulos/indice.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}{{modulo.titulo}}{% endblock title %}

{% block body %}
<div class="container mt-5 mb-5">
    {% for modulo in modulos %}
    <div class="row">
        <div class="col-md-12">
            <h1 class="mt-4 mb-3">{{ modulo.titulo }}</h1>
            <dl>
                <dt>Público</dt>
                <dd>{{ modulo.publico }}</dd>
                <dt>Descrição</dt>
                <dd>{{ modulo.descricao }}</dd>
            </dl>
            <h2>Aulas:</h2>
            <ol>
                {% for aula in modulo.aulas %}
                <li><a href="{{ aula.get_absolute_url }}">{{ aula.titulo }}</a></li>
                {% endfor %}
            </ol>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock body %}

modulos/templates/modulos/modulo_detalhe.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}{{modulo.titulo}}{% endblock title %}

{% block body %}
<div class="container mt-5 mb-5">
    <div class="row">
        <div class="col-md-12">
            <h1 class="mt-4 mb-3">{{ modulo.titulo }}</h1>
            <dl>
                <dt>Público</dt>
                <dd>{{ modulo.publico }}</dd>
                <dt>Descrição</dt>
                <dd>{{ modulo.descricao }}</dd>
            </dl>
            <h2>Aulas:</h2>
            <ol>
                {% for aula in aulas %}
                <li><a href="{{ aula.get_absolute_url }}">{{ aula.titulo }}</a></li>
                {% endfor %}
            </ol>
        </div>
    </div>
</div>
{% endblock body %}

turmas/templates/turmas/indice.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Pagina com todas as turmas do curso Python Pro{% endblock title %}

{% block body %}
<div class="container mt-5 mb-5">
    {% for modulo in modulos %}
    <div class="row">
        <div class="col-md-12">
            <h1 class="mt-4 mb-3">{{ modulo.titulo }}</h1>
            <dl>
                <dt>Público</dt>
                <dd>{{ modulo.publico }}</dd>
                <dt>Descrição</dt>
                <dd>{{ modulo.descricao }}</dd>
            </dl>
            <h2>Aulas:</h2>
            <ol>
                {% for aula in modulo.aulas %}
                <li><a href="{{ aula.get_absolute_url }}">{{ aula.titulo }}</a></li>
                {% endfor %}
            </ol>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock body %}